%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: FTSEOptionsData.xlsx
%    Worksheet: Calls
%
% Auto-generated by MATLAB on 25-Mar-2019 19:32:32

%% Setup the Import Options
function data = importOptions(sheet)

    opts = spreadsheetImportOptions("NumVariables", 84);

    % Specify sheet and range
    opts.Sheet = sheet;
    opts.DataRange = "A3:CF277";

    % Specify column names and types
    opts.VariableNames = ["Name", "CALLESXJAN194000", "CALLESXJAN194800", "CALLESXJAN195200", "CALLESXJAN195375", "CALLESXJAN195600", "CALLESXJAN195800", "CALLESXJAN195900", "CALLESXJAN196000", "CALLESXJAN196100", "CALLESXJAN196150", "CALLESXJAN196200", "CALLESXJAN196250", "CALLESXJAN196300", "CALLESXJAN196350", "CALLESXJAN196400", "CALLESXJAN196450", "CALLESXJAN196475", "CALLESXJAN196500", "CALLESXJAN196525", "CALLESXJAN196550", "CALLESXJAN196575", "CALLESXJAN196600", "CALLESXJAN196625", "CALLESXJAN196650", "CALLESXJAN196675", "CALLESXJAN196700", "CALLESXJAN196725", "CALLESXJAN196750", "CALLESXJAN196775", "CALLESXJAN196800", "CALLESXJAN196825", "CALLESXJAN196850", "CALLESXJAN196875", "CALLESXJAN196900", "CALLESXJAN196925", "CALLESXJAN196950", "CALLESXJAN196975", "CALLESXJAN197000", "CALLESXJAN197025", "CALLESXJAN197050", "CALLESXJAN197075", "CALLESXJAN197100", "CALLESXJAN197125", "CALLESXJAN197150", "CALLESXJAN197175", "CALLESXJAN197200", "CALLESXJAN197225", "CALLESXJAN197250", "CALLESXJAN197275", "CALLESXJAN197300", "CALLESXJAN197325", "CALLESXJAN197350", "CALLESXJAN197375", "CALLESXJAN197400", "CALLESXJAN197425", "CALLESXJAN197450", "CALLESXJAN197475", "CALLESXJAN197500", "CALLESXJAN197525", "CALLESXJAN197550", "CALLESXJAN197575", "CALLESXJAN197600", "CALLESXJAN197625", "CALLESXJAN197650", "CALLESXJAN197675", "CALLESXJAN197700", "CALLESXJAN197725", "CALLESXJAN197750", "CALLESXJAN197775", "CALLESXJAN197800", "CALLESXJAN197825", "CALLESXJAN197850", "CALLESXJAN197875", "CALLESXJAN197900", "CALLESXJAN198000", "CALLESXJAN198100", "CALLESXJAN198200", "CALLESXJAN198400", "CALLESXJAN198600", "CALLESXJAN198800", "CALLESXJAN199200", "CALLESXJAN199600", "CALLESXJAN1910400"];
    opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

    % Import the data
    data = readtable("Data/FTSEOptionsData.xlsx", opts, "UseExcel", false);


    %% Clear temporary variables
    clear opts
end